import { test, expect } from '@playwright/test';

test('seed script generates 500+ cards and lists virtualize large lists', async ({ page }) => {
  // Visit with seed flag which loads /seed-state.js generated by `npm run seed`
  await page.goto('/?seed=true');

  // Wait until localStorage is populated by the seed script
  await page.waitForFunction(() => !!window.localStorage.getItem('kanban-board-state'));

  const raw = await page.evaluate(() => window.localStorage.getItem('kanban-board-state'));
  const state = JSON.parse(raw || '{}');

  expect(state.cards).toBeDefined();
  expect(state.cards.length).toBeGreaterThanOrEqual(500);

  // Find any list that contains more than 30 cards
  const counts = (state.lists || []).map(l => ({ id: l.id, title: l.title, count: (state.cards || []).filter(c => c.listId === l.id).length }));
  const big = counts.find(c => c.count > 30);
  expect(big).toBeDefined();

  // Confirm the UI shows the list count and that visible card nodes are fewer than the total (virtualization)
  await page.waitForSelector('h3');
  const header = await page.locator('h3', { hasText: big.title }).first();
  await expect(header).toContainText(`(${big.count})`);

  // Count rendered card items in the DOM (should be much less than total thanks to virtualization)
  const visibleCards = await page.locator('[data-testid="card-item"]').count();
  expect(visibleCards).toBeLessThan(big.count);
});