// scripts/seed-data.js
/**
 * Seed script to generate N cards for performance testing (default 500).
 * 
 * Usage:
 *   node scripts/seed-data.js [count]
 *   npm run seed -- 600
 *
 * This populates localStorage with a realistic board state
 * containing 3 lists and `count` cards, and writes `public/seed-state.js`
 * so you can load the data into the browser by visiting `?seed=true`.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

(() => {
  // Simple UUID-like ID generator (for seed only — not cryptographically secure)
  const generateId = () => Math.random().toString(36).substring(2, 15);

  const now = Date.now();
  const argv = process.argv.slice(2);
  const count = Math.max(1, parseInt(argv[0], 10) || 500);

  // Create 3 lists (matches initialState in boardReducer.js)
  const lists = [
    { id: 'list-todo', title: 'To Do', order: 0, archived: false, version: 1, lastModifiedAt: now },
    { id: 'list-progress', title: 'In Progress', order: 1, archived: false, version: 1, lastModifiedAt: now },
    { id: 'list-done', title: 'Done', order: 2, archived: false, version: 1, lastModifiedAt: now },
  ];

  // Generate `count` cards distributed across lists
  const cards = [];
  const listIds = lists.map(l => l.id);
  for (let i = 1; i <= count; i++) {
    const listId = listIds[Math.floor(Math.random() * listIds.length)];
    cards.push({
      id: `card-${generateId()}`,
      listId: listId,
      title: `Task ${i}`,
      description: `This is the description for task ${i}. It includes some sample text to simulate real-world content length.`,
      tags: i % 7 === 0 ? ['bug'] : i % 5 === 0 ? ['feature'] : i % 3 === 0 ? ['ui'] : [],
      version: 1,
      lastModifiedAt: now - Math.floor(Math.random() * 86400000), // Random time in last 24h
    });
  }

  // Construct full board state
  const state = { lists, cards };

  // Save to localStorage if running in a browser
  if (typeof localStorage !== 'undefined') {
    localStorage.setItem('kanban-board-state', JSON.stringify(state));
    console.log(`✅ Successfully seeded ${cards.length} cards into localStorage`);
    console.log(`   - Lists: ${lists.length}`);
    console.log(`   - Cards: ${cards.length}`);
    return;
  }

  // Otherwise (Node) write a small JS file into /public that sets the state when loaded in the browser

  try {
    const out = `// Auto-generated by scripts/seed-data.js\n(function(){\n  try{\n    localStorage.setItem('kanban-board-state', ${JSON.stringify(JSON.stringify(state))});\n    console.log('✅ Seeded state into localStorage via /seed-state.js');\n  }catch(e){console.error('Failed to seed state:', e);}\n})();\n`;

    const outPath = path.join(__dirname, '..', 'public', 'seed-state.js');
    fs.writeFileSync(outPath, out, 'utf8');
    console.log(`✅ Wrote seed script to ${outPath}`);
    console.log('Open the dev server with `npm run dev` and visit: http://localhost:5173/?seed=true to load the seeded state into localStorage.');
  } catch (e) {
    console.error('❌ Failed to write seed file:', e);
    process.exit(1);
  }
})();